#!/bin/bash

option=$1
coverFile=$2
password=$(cat password.txt)

if [[ $option == "em"]]; then
    nano message.txt
    steghide embed -cf $coverFile -ef message.txt -p $password
    rm message.txt
elif [[ $option == "ex"]]; then
    steghide extract -sf $coverFile -p $password
    cat message.txt
    rm message.txt
else 
    echo "Invalid command"
fi